### ISSUE TITLE
error starting container

### ISSUE THREAD

**Issue by h0lzi** [joyent/sdc-docker#6]
simple docker run -d busybox or ubuntu does fail.

joyent_20150226T035656Z

Logs:

[2015-02-26T11:16:55.419Z] ERROR: docker/17201 on 37c28548-fe91-40d6-befb-db5f604fe125: Error starting container. (req_id=cef5d410-bda8-11e4-a390-bb4d7cff2b5e)
    InternalServerError: {"message":"job start-7.0.5 (bb786abb-6519-4906-a4a9-de994467b793) failed: vmapi.check_state: task timeout error"}
        at ClientRequest.onResponse (/opt/smartdc/docker/node_modules/restify/lib/clients/http_client.js:161:26)
        at ClientRequest.g (events.js:180:16)
        at ClientRequest.emit (events.js:95:17)
        at HTTPParser.parserOnIncomingClient (http.js:1692:21)
        at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:121:23)
        at HTTPParser.parser.execute (/opt/smartdc/docker/lib/hijack.js:54:27)
        at Socket.socketOnData (http.js:1587:20)
        at TCP.onread (net.js:527:27)

Starting the zone by hand (if that is at all supported) does not work either.
There seems to be a problem in the lx/docker start code.
Not sure if the ticket should be placed here or in illumos-joyent

**Comment by misterbisson** [comment]
Have you updated all the services as described in https://www.joyent.com/blog/test-drive-joyents-elastic-container-infrastructure-for-docker ?

```
sdcadm self-update
sdcadm update --all -y
sdcadm experimental update-docker

**Comment by h0lzi** [comment]
yes updated all the way. To latest stuff.

**Comment by h0lzi** [comment]
ok updated now again to latest stuff. What I see is docker container is created and the starting then fails:
even though the logs tell it was startet:

[2015-02-27T08:32:44.671Z] DEBUG: docker/18833 on 37c28548-fe91-40d6-befb-db5f604fe125: Found 1 VMs (req_id=33ab4040-be5b-11e4-91cf-4d40a1cfdf68)
[2015-02-27T08:32:44.671Z] DEBUG: docker/18833 on 37c28548-fe91-40d6-befb-db5f604fe125: start_params: {"owner_uuid":"930896af-bf8c-48d4-885c-6573a94b1853","uuid":"7d3aa70a-4d24-4582-9f61-e1b9db20299e","sync":true} (req_id=33ab4040-be5b-11e4-91cf-4d40a1cfdf68)
[2015-02-27T08:32:59.737Z] DEBUG: docker/18833 on 37c28548-fe91-40d6-befb-db5f604fe125: created start job (req_id=33ab4040-be5b-11e4-91cf-4d40a1cfdf68)
    job: {
      "vm_uuid": "7d3aa70a-4d24-4582-9f61-e1b9db20299e",
      "job_uuid": "bea1f681-ff7b-4a64-9d78-43fcd6937a7c"
    }
[2015-02-27T08:32:59.737Z]  INFO: docker/18833 on 37c28548-fe91-40d6-befb-db5f604fe125:  (req_id=33ab4040-be5b-11e4-91cf-4d40a1cfdf68)
    evt: {
      "ph": "e",
      "name": "containerstart"
    }
[2015-02-27T08:32:59.738Z]  INFO: docker/audit/18833 on 37c28548-fe91-40d6-befb-db5f604fe125: handled: 204 (req_id=33ab4040-be5b-11e4-91cf-4d40a1cfdf68, route=containerstart, audit=true, remoteAddress=10.88.88.1, remotePort=50530, latency=15126, _audit=true, req.version=*)
    POST /v1.17/containers/7d3aa70a4d2445829f61e1b9db20299ed45efa44a18d4daeab021a27e0a3b5e9/start HTTP/1.1
    host: 10.88.88.6:2375
    user-agent: Docker-Client/1.5.0
    content-length: 0
    content-type: text/plain
    accept-encoding: gzip
    --
    HTTP/1.1 204 No Content
    date: Fri, 27 Feb 2015 08:32:59 GMT
    x-request-id: 33ab4040-be5b-11e4-91cf-4d40a1cfdf68
    x-response-time: 15125
    --
    req.timers: {
      "handler-0": 16,
      "bunyan": 36,
      "handler-2": 115,
      "parseQueryString": 15,
      "readBody": 24,
      "parseBody": 9,
      "getAccount": 226,
      "checkServices": 7,
      "checkApiVersion": 16,
      "containerStart": 15125273
    }


what I see on the head node is this:

28 7d3aa70a-4d24-4582-9f61-e1b9db20299e ready      /zones/7d3aa70a-4d24-4582-9f61-e1b9db20299e lx       excl  

 28 7d3aa70a-4d24-4582-9f61-e1b9db20299e running    /zones/7d3aa70a-4d24-4582-9f61-e1b9db20299e lx       excl

28 7d3aa70a-4d24-4582-9f61-e1b9db20299e shutting_down /zones/7d3aa70a-4d24-4582-9f61-e1b9db20299e lx       excl

- 7d3aa70a-4d24-4582-9f61-e1b9db20299e installed  /zones/7d3aa70a-4d24-4582-9f61-e1b9db20299e lx       excl  

in a short timeframe. So it does try to start but then shuts down for some reason.
Is there a zone start debug so I can see what is going on there?

**Comment by askfongjojo** [comment]
Hi Jan,

What image did you use for the container? (Busybox?)

Also when you do docker ps -a, is the container showing a non-zero exit code?

Angela

**Comment by h0lzi** [comment]
yes was busybox image.

docker run -d busybox
a6406a8141a545cc952573b38f3aa396d04a226cf08345adb1e528017c10e565

FATA[0085] Error response from daemon: problem starting container 
[1]    31300 exit 1     docker run -d busybox


docker ps is empty afterwards

**Comment by h0lzi** [comment]
updated this morning to the latest stuff. Still same problem:
joyent_20150302T052444Z
SERVICE VERSION
adminui master-20150227T103741Z-g675edc8
amon master-20150226T075046Z-g58ecaf8
amonredis master-20150226T080620Z-g4bbca77
assets master-20150226T080059Z-g6012d50
binder master-20150226T080343Z-gba090a8
ca master-20150226T080141Z-gb775d2d
cloudapi master-20150227T192746Z-gf2fe2f2
cnapi master-20150227T172612Z-gf19ccdc
dhcpd master-20150301T193123Z-g0a9c3c0
docker master-20150302T070536Z-g5a41c5a
fwapi master-20150226T081200Z-g8601d56
hostvolume master-20150226T074943Z-g20cd789
imgapi master-20150226T074935Z-gf69e4d4
mahi master-20150226T185448Z-g4e3f5d9
manatee master-20150227T191223Z-gad45608
moray master-20150227T190616Z-gf7607c7
napi master-20150226T074910Z-gbc4a87c
papi master-20150226T081600Z-g7905a77
rabbitmq release-20150219-20150219T092536Z-gb1ad38d
redis master-20150226T081228Z-g0d6e5b9
sapi master-20150226T082326Z-g14fa2e4
sdc master-20150226T081811Z-g98a10a1
ufds master-20150226T075650Z-g9a66af3
vmapi master-20150228T054919Z-gb09aea6
workflow master-20150226T081626Z-g2a160f5

**Comment by joshwilsdon** [comment]
```
docker run -d busybox
``` 

doesn't make sense as a command since you're telling it to run /bin/sh (the default) in the background with no stdin attach. In this case bash will always exit.

Assuming what you want is an interactive shell, what you probably want is:

```
docker run -it busybox
```

If it still doesn't work with that command, please re-open.
